FROM resin/%%RESIN_MACHINE_NAME%%-python

RUN apt-get update && apt-get install -yq \
   sense-hat && \
   apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY . ./

ENV INITSYSTEM on

CMD modprobe i2c-dev && python src/main.py